title: Insulator
email: andrewinci@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andrewinci
github_username:  andrea-vinci


# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

collections:
  wiki:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    wiki:
      name: Documentation