name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ktlint
      run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.39.0/ktlint && chmod a+x ktlint
    - name: Run ktlint
      run: ./ktlint -F